import type { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

interface ResourceIdOperation extends Omit<INodePropertyOptions, 'routing'> {
	path: string;
}

export function createResourceIdOperation({
	path,
	...metadata
}: ResourceIdOperation): INodePropertyOptions {
	return {
		...metadata,
		routing: {
			request: {
				method: 'POST',
				url: path,
				headers: {
					'Content-Type': 'application/json',
				},
			},
		},
	};
}

interface ResourceIdFieldOptions {
	inputType?: string;
}

export function createResourceIdField(
	operation: string,
	{ inputType }: ResourceIdFieldOptions = {},
): INodeProperties {
	return {
		displayName: 'Resource ID',
		name: 'resourceId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				operation: [operation],
				...(inputType ? { inputType: [inputType] } : {}),
			},
		},
		description: 'The ID of a file previously uploaded or generated by pdfRest',
		routing: {
			send: {
				type: 'body',
				property: 'id',
			},
		},
	};
}
