import type {
	IExecuteSingleFunctions,
	IHttpRequestOptions,
	IN8nHttpFullResponse,
	INodeExecutionData,
	INodeProperties,
	INodePropertyOptions,
	PreSendAction,
} from 'n8n-workflow';
import { getPdfRestBaseUrl } from '../helpers/baseUrl';
import { createIncludeFileInfoField } from '../helpers/headers';
import { prepareDownloadedBinaryData } from '../helpers/outputDownload';

const prepareResourceResponse: PreSendAction = async function prepareResourceResponse(
	requestOptions,
): Promise<IHttpRequestOptions> {
	if (this.getNodeParameter('format') !== 'file') {
		return requestOptions;
	}

	requestOptions.encoding = 'arraybuffer';
	requestOptions.headers = {
		...requestOptions.headers,
		Accept: '*/*',
	};

	return requestOptions;
};

async function addResourceBinaryMetadata(
	this: IExecuteSingleFunctions,
	items: INodeExecutionData[],
	response: IN8nHttpFullResponse,
): Promise<INodeExecutionData[]> {
	if (this.getNodeParameter('format') !== 'file') {
		return items;
	}

	const outputFieldName = this.getNodeParameter('outputFileDataFieldName') as string;
	const resourceId = this.getNodeParameter('resourceId') as string;
	const credentials = await this.getCredentials('pdfRestApi');
	const baseUrl = getPdfRestBaseUrl(credentials);
	const downloadUrl = `${baseUrl}/resource/${encodeURIComponent(resourceId)}?format=file`;
	const binaryData = await prepareDownloadedBinaryData(this, response, downloadUrl);

	return items.map((item) => ({
		...item,
		json: {},
		binary: {
			...item.binary,
			[outputFieldName]: binaryData,
		},
	}));
}

export const getResourceOperation: INodePropertyOptions = {
	name: 'Retrieve Resource or Its URL by ID',
	value: 'getResource',
	action: 'Files · Retrieve Files by ID',
	description: 'Retrieve a pdfRest resource file, its download URL, or metadata using its ID',
	routing: {
		request: {
			method: 'GET',
			url: '=/resource/{{$parameter.resourceId}}',
		},
	},
};

export const getResourceDescription: INodeProperties[] = [
	{
		displayName: 'Resource ID',
		name: 'resourceId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				operation: ['getResource'],
			},
		},
		description: 'The ID of a file previously uploaded or generated by pdfRest',
	},
	{
		displayName: 'Format',
		name: 'format',
		type: 'options',
		options: [
			{
				name: 'File',
				value: 'file',
			},
			{
				name: 'URL',
				value: 'url',
			},
			{
				name: 'File Information',
				value: 'info',
			},
		],
		default: 'url',
		required: true,
		displayOptions: {
			show: {
				operation: ['getResource'],
			},
		},
		description: 'Choose whether to return the file, its URL, or information about the file',
		routing: {
			send: {
				type: 'query',
				property: 'format',
				preSend: [prepareResourceResponse],
			},
			output: {
				postReceive: [addResourceBinaryMetadata],
			},
		},
	},
	{
		displayName: 'Output File Data Field Name',
		name: 'outputFileDataFieldName',
		type: 'string',
		default: 'data',
		required: true,
		displayOptions: {
			show: {
				operation: ['getResource'],
				format: ['file'],
			},
		},
		description: 'The name of the output field where the retrieved file is stored',
	},
	{
		displayName: 'Optional Fields',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['getResource'],
			},
		},
		options: [createIncludeFileInfoField('getResource')],
	},
];
